[params]
ShowReadingTime = true
archiveByDefault = true # use archive layout for home

[params.fuseOpts] # need this for search
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]


[[menu.main]]
  name = "Misc"
  weight = 3
  url = "/misc"
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags"
  weight = 2
[[menu.main]]
  name = "ğŸ¹"
  url = "/music"
  weight = 4
[[menu.main]]
  name = "ğŸ”–"
  weight = 5
  url = "/bookmarks"
#[[menu.main]] # for PaperMod
#  name = "ğŸ”"
#  weight = 6
#  url = "/search"

[params.homeInfoParams]
#Title = "KONOMAMA's BLOG"
Content = """
- æœ¬blogéƒ¨åˆ†å¤–é“¾åŠå†…åµŒå†…å®¹ğŸ‡¨ğŸ‡³éœ€vpn (æœ‰å¾ˆå¤šyoutube, googleç³»æœåŠ¡, wikié“¾æ¥)
- æœ‰ä»»ä½•éœ€è¦æ¬¢è¿ç•™è¨€(é‚®ç®±éå¿…å¡«ï¼Œé™¤éè®¢é˜…å¯¹è¯)
- è‹¥è®¢é˜…å¯¹è¯è¯·æ£€æŸ¥åƒåœ¾é‚®ä»¶: `mail.konomama.dev@gmail.com`
- è¯·è°¨æ…åˆ†äº«æœ¬blogæ–‡ç« åˆ°å¾®ä¿¡ï¼Œè…¾è®¯ä¼šè‡ªåŠ¨ç”¨çˆ¬è™«çˆ¬å–è¢«åˆ†äº«çš„æ–‡ç« ï¼Œå¯èƒ½æ˜¯è¦æ£€æµ‹æ˜¯å¦æœ‰â€œéæ³•å†…å®¹â€
"""

[[params.socialIcons]]
name = "rss"
url = "https://blog.konomama.dev/index.xml"
#[[params.socialIcons]]
#name = "bilibili"
#url = "https://space.bilibili.com/1497254925/"
[[params.socialIcons]]
name = "lastfm"
url = "https://www.last.fm/user/iloveWinnie"
[[params.socialIcons]]
name = "steam"
url = "https://steamcommunity.com/profiles/76561198844206094"

[markup.highlight]
#noClasses = false #comment out if you use paperMod chroma
codeFences = true
guessSyntax = true
lineNos = false
hl_inline = false
style = "monokai" #"solarized-light" "github"
[params.assets]
disableHLJS = true
pygmentsUseClasses = true