[params.fuseOpts] # need this for search
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
  name = "Archive" # for PaperMod
  weight = 1
  url  = "/archive/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "/about"
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags"
  weight = 3
[[menu.main]]
  name = "ğŸ”–"
  weight = 5
  url = "/bookmarks"
[[menu.main]] # for PaperMod
  name = "Search"
  weight = 4
  url = "/search"

[params.homeInfoParams]
#Title = "KONOMAMA's BLOG"
Content = """
- æœ¬blogæœåŠ¡å™¨ä¸åœ¨ä¸­å›½ï¼Œä½†æœåŠ¡å™¨æœ¬èº«æ²¡æœ‰è¢«å¢™ï¼Œæ‰€ä»¥ä»ä¸­å›½å¢ƒå†…å¯ä»¥ä¸ç”¨vpnç›´æ¥æ‰“å¼€
- æœ¬blogç¦æ­¢äº†ä¸­å›½æœç´¢å¼•æ“çš„çˆ¬è™«ï¼Œæ‰€ä»¥åªèƒ½ç”¨googleæœç´¢åˆ°
- æœ¬blogæœåŠ¡å™¨å’Œåå°ç¨‹åºç”±æœ¬äººæ§åˆ¶ï¼Œä¸å—å®¡æ ¸é™åˆ¶
- æœ¬blogå¤§éƒ¨åˆ†å¤–é“¾ä¸­å›½å¢ƒå†…éœ€è¦vpnè®¿é—®
"""

#[[params.socialIcons]]
#name = "rss"
#url = "https://blog.konomama.dev/index.xml"
[[params.socialIcons]]
name = "bilibili"
url = "https://space.bilibili.com/1497254925/"
[[params.socialIcons]]
name = "lastfm"
url = "https://www.last.fm/user/iloveWinnie"

[markup.highlight]
#noClasses = false #comment out if you use paperMod chroma
codeFences = true
guessSyntax = true
lineNos = false
style = "github" #"solarized-light" "github"
[params.assets]
disableHLJS = true
pygmentsUseClasses = true